trigger:
- updates/strategy-tweak

#required - add in the below variables
variables:
#  REGISTRYURL: <insert name here>.azurecr.io
#  REGISTRY_USERNAME: ??
#  REGISTRY_PASSWORD: ??  #use secret here!

jobs:
- job: Build_images
  displayName: Build images
  strategy:
    matrix:
      Linux:
        vmImage: 'ubuntu-16.04'
        imageName: 'linux-arm'
        dockerfile: 'Dockerfile.Linux'
      MacOS:
        vmImage: 'ubuntu-16.04'
        imageName: 'linux-x64'
        dockerfile: 'Dockerfile.Linux'
      Windows:
        vmImage: 'windows-latest'
        imageName: 'windows-x64'
        dockerfile: 'Dockerfile.Windows'
  pool:
    vmImage: $(vmImage)
  steps:
  - template: yml-steps/build-and-push.yml
    parameters:
      targetStage: $(imageName)
      repository: 'myapp'
      dockerfile: $(dockerfile)

- job: Push_Manifest_List
  dependsOn:
  - Build_images
  displayName: Push Manifest List
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - template: yml-steps/create-manifest-list.yml
    parameters:
      manifestName: 'myapp'
      childImages: '$REGISTRYURL/myapp:${BUILD_BUILDID}-linux-x64 $REGISTRYURL/myapp:${BUILD_BUILDID}-linux-arm $REGISTRYURL/myapp:${BUILD_BUILDID}-windows-x64'